name: cup_of_tea
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  dio: ^4.0.6
  mask_text_input_formatter: ^2.4.0
  flutter_secure_storage: ^6.0.0
  injectable: ^1.5.3
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  retrofit: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.1.4
  # bloc_test: ^9.0.2
  # mocktail: ^0.2.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  injectable_generator: ^1.5.3
  retrofit_generator: '>=4.0.0 <5.0.0'
  environment_config: ^3.1.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
